---

- name: golang - include_vars
  include_vars: '{{ item }}'
  with_first_found:
  - files:
    - '{{ ansible_distribution_id }}_vars.yml'
    - '{{ ansible_distribution }}_vars.yml'
    - '{{ ansible_os_family }}_vars.yml'
    - '{{ ansible_system }}_vars.yml'
    skip: true

- name: golang - include task
  include: '{{ system_item }}'
  with_first_found:
    - '{{ ansible_os_family }}/main.yml'
    - '{{ ansible_system }}/main.yml'
    - unsupported.yml
  loop_control:
    loop_var: system_item
