version: "2"
run:
  modules-download-mode: readonly
  issues-exit-code: 1
linters:
  default: none
  enable:
    - revive
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/elastic/go-sysinfo
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
