---

- name: check if gvm is installed
  win_stat:
    path: '{{ gvm_windows_path }}'
  changed_when: false
  register: gvm_is_present

- name: install gvm if absent
  win_get_url:
    url: "https://github.com/andrewkroh/gvm/releases/download/v{{ gvm_version }}/gvm-{{ gvm_arch }}.exe"
    dest: '{{ gvm_windows_path }}'
  when: gvm_is_present.stat.exists == False

##### BLOCK START
- block:
  - name: get gvm version if present
    win_shell: '{{ gvm_windows_path }} --version'
    register: gvm_current_version
    changed_when: false

  - name: upgrade gvm to the specified version
    get_url:
      url: "https://github.com/andrewkroh/gvm/releases/download/v{{ gvm_version }}/gvm-{{ gvm_arch }}.exe"
      dest: '{{ gvm_windows_path }}'
      force: True
    when: >
      gvm_current_version.stderr | default('') | replace('v','') | version_compare(gvm_version, '<')
  when: gvm_is_present.stat.exists == True
##### BLOCK END
