// Code generated by cmd/cgo -godefs; and then patched up to fix
// an alignment issue
// cgo -godefs defs_freebsd.go

package freebsd

type vmTotal struct {
	Rq     int16
	Dw     int16
	Pw     int16
	Sl     int16
	_      int16 // cgo doesn't generate the same alignment as C does
	Sw     int16
	Vm     int32
	Avm    int32
	Rm     int32
	Arm    int32
	Vmshr  int32
	Avmshr int32
	Rmshr  int32
	Armshr int32
	Free   int32
}

type kvmSwap struct {
	Devname   [32]int8
	Used      uint32
	Total     uint32
	Flags     int32
	Reserved1 uint32
	Reserved2 uint32
}

type clockInfo struct {
	Hz     int32
	Tick   int32
	Spare  int32
	Stathz int32
	Profhz int32
}
