---

- include: ../common/unix.yml

- name: Install build tools (git, make)
  pkgng:
    name: git,gmake
  become: true

- name: Create make - gmake symlink
  file:
    src: /usr/local/bin/gmake
    dest: /usr/local/bin/make
    state: link
  become: true
