---

- name: check if gvm is installed
  stat:
    path: '{{ gvm_unix_path }}'
  changed_when: false
  register: gvm_is_present

- name: install gvm if absent
  get_url:
    url: "https://github.com/andrewkroh/gvm/releases/download/v{{ gvm_version }}/gvm-{{ gvm_arch }}"
    dest: '{{ gvm_unix_path }}'
    mode: '0555'
    owner: root
    group: 0
  when: gvm_is_present.stat.exists == False

##### BLOCK START
- block:
  # gvm reports the version in stderr, redirect to stdout for future safety
  - name: get gvm version if present
    shell: '{{ gvm_unix_path }} --version 2>&1'
    register: gvm_current_version
    changed_when: false

  - name: upgrade gvm to the specified version
    get_url:
      url: "https://github.com/andrewkroh/gvm/releases/download/v{{ gvm_version }}/gvm-{{ gvm_arch }}"
      dest: '{{ gvm_unix_path }}'
      mode: '0555'
      owner: root
      group: 0
      force: True
    when: >
      gvm_current_version.stdout | default('') | replace('v','') | version_compare(gvm_version, '<')
  when: gvm_is_present.stat.exists == True
##### BLOCK END
