---

- name: Install Go
  command: gvm '{{ gvm_go_version }}'

- name: Set golang_goroot var
  set_fact:
    golang_goroot: '{{ ansible_user_dir }}/.gvm/versions/go{{ gvm_go_version }}.{{ gvm_arch | regex_replace("-", ".") }}'

- name: tests - update bashrc with goroot
  lineinfile:
    path: '{{ global_profile_file }}'
    line: 'eval "$(gvm {{ gvm_go_version }})"'
    regexp: '^eval.*gvm'
    create: true
  become: true

- name: tests - update bashrc to add gopath
  lineinfile:
    path: "{{ ansible_user_dir }}/{{ user_profile_file }}"
    line: "export GOPATH=/home/{{ ansible_user_id }}/go"
    regexp: '^export GOPATH'
    create: true

- name: tests - update bashrc to add gopath/bin to path
  lineinfile:
    path: "{{ ansible_user_dir }}/{{ user_profile_file }}"
    line: 'export PATH="${GOPATH}/bin:${PATH}"'
    regexp: '^export PATH.*GOPATH'
    create: true

- name: tests - setup gopath
  file:
    path: "{{ ansible_user_dir }}/go/src/github.com/elastic"
    state: directory

