---

- name: Install git
  win_chocolatey:
    name: git
    state: present

- name: Install Go
  win_command: 'gvm.exe {{ gvm_go_version }}'

- name: Set golang_goroot var
  set_fact:
    golang_goroot: '{{ ansible_user_dir }}\.gvm\versions\go{{ gvm_go_version }}.{{ gvm_arch | regex_replace("-", ".") }}'

- name: 'Set GOROOT for {{ ansible_user_id }}'
  win_environment:
    state: present
    name: GOROOT
    value: '{{ golang_goroot }}'
    level: user

- name: 'Set GOPATH for {{ ansible_user_id }}'
  win_environment:
    state: present
    name: GOPATH
    value: '{{ ansible_user_dir }}\go'
    level: user

- name: 'Add GOROOT and GOPATH to PATH for {{ ansible_user_id }}'
  win_path:
    name: PATH
    elements:
    - '%GOPATH%\bin'
    - '%GOROOT%\bin'
    scope: user
